apiVersion: apps/v1

kind: Deployment

metadata:
  name:
    deployment-ghost
  labels:
    env: prod
    app: ghost-app
  

spec:
  template:
    metadata:
      name: ghost-app-pod
      labels:
        app:  ghost-app
        env:  production
    spec:
      containers:
        - name: ghost
          image: arm32v7/ghost
          imagePullPolicy: IfNotPresent
          volumeMounts:
           - mountPath: /var/lib/ghost/content
             name: ghost-blog-data
          securityContext:
            privileged: True

      volumes:
      - name: ghost-blog-data
        persistentVolumeClaim:
          claimName: pvc-ghost



  replicas: 6

  selector:
    matchLabels:
      app: ghost-app



